### PR TITLE
Security update eslint to >= 6.2.1 and eslint-util >= 1.4.1

### PR DESCRIPTION
**Pull request by ryandberger**

### CODE REVIEW

**Comment by doytch** [comment]
Do we need to update [`eslint-config-stripes`](https://github.com/folio-org/eslint-config-stripes/blob/master/package.json) as well for this? Not just its `eslint` dependencies, but also the plugins?

**Comment by ryandberger** [comment]
> Do we need to update [`eslint-config-stripes`](https://github.com/folio-org/eslint-config-stripes/blob/master/package.json) as well for this? Not just its `eslint` dependencies, but also the plugins?

I'll take a look at that. Thanks for pointing it out!

**Comment by ryandberger** [comment]
> > Do we need to update [`eslint-config-stripes`](https://github.com/folio-org/eslint-config-stripes/blob/master/package.json) as well for this? Not just its `eslint` dependencies, but also the plugins?
> 
> I'll take a look at that. Thanks for pointing it out!

Actually, since [`eslint-config-stripes`](https://github.com/folio-org/eslint-config-stripes/blob/master/package.json) manages the version of `eslint`, I propose moving `eslint` to `peerdependencies` with version `*`. Does that make sense to everyone? If so, I will be using that approach in other repos that use `eslint`.

**Comment by dltj** [comment]
Ping.  Can we merge or close this request, please?  It is consuming AWS resources until we make a decision.

**Comment by ryandberger** [comment]
> Ping. Can we merge or close this request, please? It is consuming AWS resources until we make a decision.

I will need to update after I release `eslint-config-stripes` so I will close this for now.

**Comment by dltj** [comment]
Thanks, Ryan...I terminated the instance.

**Pull request closed without merging**
