### PR TITLE
[DO NOT MERGE] FOLIO-2471: Item mark withdrawn preview.

### PR DESCRIPTION
**Pull request by bohdan-suprun**

### CODE REVIEW

**Comment by funkymalc** [comment]
@bohdan-suprun - I think you specified the preview artifact versions incorrectly in .pr-custom-deps.json.   For example, mod-inventory-storage should be specified as 'mod-inventory-storage:19.2.0-SNAPSHOT.420.4' .  '420' represents the PR number.   Same with mod-inventory.

**Comment by bohdan-suprun** [comment]
Hi @funkymalc, I've changed the versions as you suggested, however I get another error:

`No running instances for module mod-inventory-storage-19.2.0-SNAPSHOT.420.5. Can not invoke /_/tenant`

But `https://okapi-preview.ci.folio.org/_/proxy/modules/mod-inventory-storage-19.2.0-SNAPSHOT.420.5` return descriptor. So the versions and descriptor should be correct.

**Comment by mkuklis** [comment]
@bohdan-suprun and @funkymalc I just made a small change to test the preview process from the UI perspective.

**Comment by bohdan-suprun** [comment]
Thanks @mkuklis. The flow now fails with `error Couldn't find package "@folio/quick-marc@^1.0.0" required by "@folio/inventory@folio-org/ui-inventory#UIIN-817" on the "npm" registry.` do you have any idea what should be wrong?

**Comment by funkymalc** [comment]
there is no ui-quick-marc releases yet.  I would probably change this to point to the master branch of ui-quick-marc.

**Comment by bohdan-suprun** [comment]
> there is no ui-quick-marc releases yet. I would probably change this to point to the master branch of ui-quick-marc.

Good point, @funkymalc. Trying it right now.

**Comment by bohdan-suprun** [comment]
@funkymalc, @mkuklis, it works!😄

It also required to set the master branch dependency for quick-mark in `ui-inventory` branch (see `UIIN-817-with-quick-mark-master`).

Thank you!

**Pull request closed without merging**
