### PR TITLE
STCOR-503 Satisfy react-titled peer dependency

### PR DESCRIPTION
**Pull request by skomorokh**
This enables the functionality to actually be used by apps as they need to be on the same version.

Refs [STCOR-503](https://issues.folio.org/browse/STCOR-503)

### CODE REVIEW

**Review by zburke — CHANGES_REQUESTED** [review]
Please include only the `package.json` changes. 

The other files are be automatically generated by CI processes. Including them with your PR, however, will cause CI to use them (rather than generate them) which can lead to unintended consequences if, e.g. your node repos differ. If you're doing it intentionally -- e.g. including a `yarn.lock` to overcome a cache in Jenkins -- that's OK, but that doesn't appear to be the case here.

**Comment by skomorokh** [comment]
This was my commit:
https://github.com/folio-org/platform-core/pull/799/commits/e58fe52d579d0f874b21b372b6d1d4043822dc38

Jenkins decided to do this:
https://github.com/folio-org/platform-core/pull/799/commits/4a3ddfd68ef65aaa856cccbd29b814ffb302304a

...how do I have that not happen? And at this point should I revert its commit or ..?

**Comment by funkymalc** [comment]
The extra commits are fine.   The CI will always try to update this branch.  Is this the branch you meant to merge to or did you mean to update snapshot?

**Comment by skomorokh** [comment]
@funkymalc sorry, Zak was going to handle this but then I offered to do it as I figured he was busy with the release (and that he could just merge the commits when it made sense for him) but I think he assumed I knew how these branches work. Turns out I don't :) So I'm leaving it with him to coordinate further / cherry pick to wherever they need to go.

**Pull request merged**
